title:            Edgar Sandi
description:      Posts
disqus_shortname: edgarsandi
languages: ["br", "en"]
reading_time:     true
words_per_minute: 200
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              "http://10.1.10.100:4000"

# Owner/author information
owner:
  name:           Edgar Sandi
  avatar:         edgarsandi.png
#  bio:            "Enthusiastic about Technology, Software Development, Electronics and Robotics"
  email:          edgar.r.sandi@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        edgarsandi
  facebook:       edgar.sandi
  github:         edgarsandi
  stackexchange:  
  linkedin:       edgarsandi
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/102946997383264307236?rel=author
  zendid:        ZEND014245

# Background image to be tiled on all pages
background: ps_neutral.png

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji

emoji:
  src: "/images"

# Analytics and webmaster tools stuff goes here
google_analytics: 'UA-2122720-11'
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  #- title: Theme Setup
  #  url: /theme-setup
  #- title: External Link
  #  url: http://mademistakes.com
  #  external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 1

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: table
    coderay_line_number_start: 15
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]